/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Entidades.Alumno;
import Modelo.AlumnoData;
import Modelo.Conexion;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class AlumnosVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlumnosVista
     */
    Conexion con;
    AlumnoData aData;
    public AlumnosVista() 
    {
        initComponents();
        con = new Conexion();
        aData=new AlumnoData(con);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo = new javax.swing.JLabel();
        jtfID1 = new javax.swing.JTextField();
        jlbID = new javax.swing.JLabel();
        jlbDNI = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jlbID2 = new javax.swing.JLabel();
        jlbID3 = new javax.swing.JLabel();
        jchActivo = new javax.swing.JCheckBox();
        jtbGuardar = new javax.swing.JButton();
        jtbActualizar = new javax.swing.JButton();
        jtbAnular = new javax.swing.JButton();
        jtbLimpiar = new javax.swing.JButton();
        jtbBuscar = new javax.swing.JButton();
        jtbSalir = new javax.swing.JButton();

        jlbTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jlbTitulo.setForeground(new java.awt.Color(26, 32, 0));
        jlbTitulo.setText("-ALUMNOS-");

        jlbID.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlbID.setText("ID:");

        jlbDNI.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlbDNI.setText("DNI:");

        jtfDNI.setColumns(25);

        jlbNombre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlbNombre.setText("NOMBRE:");

        jtfNombre.setColumns(25);

        jlbID2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlbID2.setText("F. NACIMIENTO:");

        jlbID3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jlbID3.setText("Activo:");

        jtbGuardar.setText("Guardar");
        jtbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbGuardarActionPerformed(evt);
            }
        });

        jtbActualizar.setText("Actualizar");

        jtbAnular.setText("Anular");

        jtbLimpiar.setText("Limpiar");

        jtbBuscar.setText("Buscar");
        jtbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbBuscarActionPerformed(evt);
            }
        });

        jtbSalir.setText("Salir");
        jtbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbAnular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbID3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchActivo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlbDNI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbLimpiar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlbID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfID1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(219, 219, 219)
                            .addComponent(jtbBuscar))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jlbTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbID2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtbSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbID)
                    .addComponent(jtfID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDNI)
                            .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombre)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbID2))
                    .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbID3)
                    .addComponent(jchActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbGuardar)
                    .addComponent(jtbActualizar)
                    .addComponent(jtbAnular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtbSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbGuardarActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        if(jtfDNI.getText()!=null&&jtfNombre.getText()!=null)
        {
            int dni = Integer.parseInt(jtfDNI.getText());
            String nombre = jtfNombre.getText();
            String fecha = formato.format(jcFecha.getDate() );
            LocalDate date= LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd-MM-yyyy"));

            boolean act= jchActivo.isSelected();

            Alumno al = new Alumno(dni,nombre,date,act);
            aData.guardarAlumno(al);
        }
    }//GEN-LAST:event_jtbGuardarActionPerformed

    private void jtbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbBuscarActionPerformed

    private void jtbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jtbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JCheckBox jchActivo;
    private javax.swing.JLabel jlbDNI;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbID2;
    private javax.swing.JLabel jlbID3;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JButton jtbActualizar;
    private javax.swing.JButton jtbAnular;
    private javax.swing.JButton jtbBuscar;
    private javax.swing.JButton jtbGuardar;
    private javax.swing.JButton jtbLimpiar;
    private javax.swing.JButton jtbSalir;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfID1;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
