/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author jackd
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumn = new javax.swing.JMenu();
        jmiManejarAlumnos = new javax.swing.JMenuItem();
        jMenuMats = new javax.swing.JMenu();
        jmiMaterias = new javax.swing.JMenuItem();
        jMenuInsc = new javax.swing.JMenu();
        jmiInscripciones = new javax.swing.JMenuItem();
        jmiCargarNotas = new javax.swing.JMenuItem();
        jMenuLists = new javax.swing.JMenu();
        jmiListarInscriptosMat = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuAlumn.setText("Alumnos");

        jmiManejarAlumnos.setText("Administrar Alumnos");
        jmiManejarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejarAlumnosActionPerformed(evt);
            }
        });
        jMenuAlumn.add(jmiManejarAlumnos);

        jMenuBar1.add(jMenuAlumn);

        jMenuMats.setText("Materias");

        jmiMaterias.setText("Administrar Materias");
        jmiMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriasActionPerformed(evt);
            }
        });
        jMenuMats.add(jmiMaterias);

        jMenuBar1.add(jMenuMats);

        jMenuInsc.setText("Manejar Inscripciones");

        jmiInscripciones.setText("Manejar Inscripciones");
        jmiInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInscripcionesActionPerformed(evt);
            }
        });
        jMenuInsc.add(jmiInscripciones);

        jmiCargarNotas.setText("Cargar Notas");
        jmiCargarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarNotasActionPerformed(evt);
            }
        });
        jMenuInsc.add(jmiCargarNotas);

        jMenuBar1.add(jMenuInsc);

        jMenuLists.setText("Listados");

        jmiListarInscriptosMat.setText("Listar Inscriptos por Materia");
        jMenuLists.add(jmiListarInscriptosMat);

        jMenuBar1.add(jMenuLists);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionesActionPerformed
      
        jEscritorio.removeAll();
        jEscritorio.repaint();
        InscripcionVista vista = new InscripcionVista();
        vista.setVisible(true);
        jEscritorio.add(vista);
        jEscritorio.moveToFront(vista);
    }//GEN-LAST:event_jmiInscripcionesActionPerformed

    private void jmiCargarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCargarNotasActionPerformed

    private void jmiMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriasActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        MateriaVista vista = new MateriaVista();
        vista.setVisible(true);
        jEscritorio.add(vista);
        jEscritorio.moveToFront(vista);
    }//GEN-LAST:event_jmiMateriasActionPerformed

    private void jmiManejarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejarAlumnosActionPerformed
        jEscritorio.removeAll();
        jEscritorio.repaint();
        AlumnosVista vista = new AlumnosVista();
        vista.setVisible(true);
        jEscritorio.add(vista);
        jEscritorio.moveToFront(vista);
    }//GEN-LAST:event_jmiManejarAlumnosActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuAlumn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInsc;
    private javax.swing.JMenu jMenuLists;
    private javax.swing.JMenu jMenuMats;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jmiCargarNotas;
    private javax.swing.JMenuItem jmiInscripciones;
    private javax.swing.JMenuItem jmiListarInscriptosMat;
    private javax.swing.JMenuItem jmiManejarAlumnos;
    private javax.swing.JMenuItem jmiMaterias;
    // End of variables declaration//GEN-END:variables
}
