package Vista;

import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {

    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        jMFormAl = new javax.swing.JMenuItem();
        jMListarAlum = new javax.swing.JMenuItem();
        jMMaterias = new javax.swing.JMenu();
        jMFormMat = new javax.swing.JMenuItem();
        jMListarM = new javax.swing.JMenuItem();
        jMInscrip = new javax.swing.JMenu();
        jMInscripciones = new javax.swing.JMenuItem();
        jMNotas = new javax.swing.JMenuItem();
        jMArchivo = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jMAlumnos.setText("Alumnos");

        jMFormAl.setText("Formulario");
        jMFormAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormAlActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMFormAl);

        jMListarAlum.setText("Listar");
        jMListarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListarAlumActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMListarAlum);

        jMenuBar1.add(jMAlumnos);

        jMMaterias.setText("Materias");

        jMFormMat.setText("Formulario");
        jMFormMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormMatActionPerformed(evt);
            }
        });
        jMMaterias.add(jMFormMat);

        jMListarM.setText("Listar");
        jMListarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListarMActionPerformed(evt);
            }
        });
        jMMaterias.add(jMListarM);

        jMenuBar1.add(jMMaterias);

        jMInscrip.setText("Inscripciones");

        jMInscripciones.setText("Formulario");
        jMInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInscripcionesActionPerformed(evt);
            }
        });
        jMInscrip.add(jMInscripciones);

        jMNotas.setText("Notas");
        jMNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNotasActionPerformed(evt);
            }
        });
        jMInscrip.add(jMNotas);

        jMenuBar1.add(jMInscrip);

        jMArchivo.setText("Salir");

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMArchivo.add(jMSalir);

        jMenuBar1.add(jMArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMFormAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormAlActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFAlumnos agregarA = new JIFAlumnos();
        agregarA.setVisible(true);
        agregarA.setBounds(500, 150, 400, 400);
        escritorio.add(agregarA);
        escritorio.moveToFront(agregarA);
    }//GEN-LAST:event_jMFormAlActionPerformed

    private void jMFormMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormMatActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFMateria matda = new JIFMateria();
        matda.setVisible(true);
        matda.setBounds(500, 150, 400, 300);
        escritorio.add(matda);
        escritorio.moveToFront(matda);
    }//GEN-LAST:event_jMFormMatActionPerformed

    private void jMInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInscripcionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFInscripcion incd = new JIFInscripcion();
        incd.setVisible(true);
        incd.setBounds(500, 150, 400, 400);
        escritorio.add(incd);
        escritorio.moveToFront(incd);
    }//GEN-LAST:event_jMInscripcionesActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "Realmente desea salir?", "Confirmar salida", JOptionPane.CLOSED_OPTION, JOptionPane.CANCEL_OPTION);
        if(opcion==0){
            System.exit(0);
        }

    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFNotas nota = new JIFNotas();
        nota.setVisible(true);
        nota.setBounds(500, 150, 400, 300);
        escritorio.add(nota);
        escritorio.moveToFront(nota);
    }//GEN-LAST:event_jMNotasActionPerformed

    private void jMListarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListarAlumActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFListarAlumnos listA = new JIFListarAlumnos();
        listA.setVisible(true);
        listA.setBounds(500, 150, 420, 300);
        escritorio.add(listA);
        escritorio.moveToFront(listA);
    }//GEN-LAST:event_jMListarAlumActionPerformed

    private void jMListarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListarMActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        JIFListarMaterias listM = new JIFListarMaterias();
        listM.setVisible(true);
        listM.setBounds(500, 150, 400, 300);
        escritorio.add(listM);
        escritorio.moveToFront(listM);
    }//GEN-LAST:event_jMListarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana vent = new Ventana();
                vent.setVisible(true);
                vent.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenuItem jMFormAl;
    private javax.swing.JMenuItem jMFormMat;
    private javax.swing.JMenu jMInscrip;
    private javax.swing.JMenuItem jMInscripciones;
    private javax.swing.JMenuItem jMListarAlum;
    private javax.swing.JMenuItem jMListarM;
    private javax.swing.JMenu jMMaterias;
    private javax.swing.JMenuItem jMNotas;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
